### ISSUE TITLE
Reconsider Langchain dependency

### ISSUE THREAD

**Issue by tomusher** [wagtail/wagtail-vector-index#10]
We rely on [langchain](https://github.com/langchain-ai/langchain/tree/master/libs/langchain/langchain) for [text splitting](https://github.com/wagtail/wagtail-vector-index/blob/e1ffce3998ab4e53855fa9bc1554347ddacb62de/src/wagtail_vector_index/models.py#L9).

This is quite a large dependency for the very small part of it we use. Consider whether it would be worth vendorising this text splitter, implementing our own, or finding a less heavyweight text splitting package.

**Comment by tomusher** [comment]
Related issue on wagtail-ai https://github.com/wagtail/wagtail-ai/issues/17

**Comment by zerolab** [comment]
Fixed by #24
