### ISSUE TITLE
Exclude current document from similarity search

### ISSUE THREAD

**Issue by tomusher** [wagtail/wagtail-vector-index#19]
When using the `similar` method on an index, the current document is returned as a similar document. This should be excluded.

**Comment by tm-kn** [comment]
In #22 I made this a concern of the Wagtail Vector Index, not the backend's. That does mean if all the similar documents are returned for the same object, then we may get no results.

Should the issue say "Exclude current indexable object from similarity search" given that each object can have one or more documents (`Embedding` instances)?

It would be nice if the backends had awareness of documents being linked and returning collections of documents, not documents. I don't think this would be possible but I did not look very deeply into it.

We could also look at making follow-up queries until we get a desired count of unique objects ("document collections") to make the results a bit more useful.
