### ISSUE TITLE
Add streaming support for 'query' calls

### ISSUE THREAD

**Issue by tomusher** [wagtail/wagtail-vector-index#48]
When building a 'chat'-like interface, it can be a nicer experience for responses to stream in rather than waiting for it all to be ready.

Implement a way to stream these responses, e.g. using server-sent events.

This should be an optional feature as it will likely require additional infrastructure.

**Comment by tomusher** [comment]
In progress on #28

**Comment by Morsey187** [comment]
In review, theres a few issues related to ASGI to reslove for related intranet work being used to test this, however, I've set aside some time each day address this.

- https://github.com/wagtail/wagtail-vector-index/pull/28

**Comment by tomusher** [comment]
Reviving this as #86
