### ISSUE TITLE
Add pg_embedding backend

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail-vector-index#5]
https://github.com/neondatabase/pg_embedding

pg_embedding is a new extension in the vector search space promissing quite a bit of speedup over pg_vector - https://neon.tech/blog/pg-embedding-extension-for-vector-search

See notes from #4

**Comment by tomusher** [comment]
Note that `pg_embedding` is no longer supported by Neon as per the repo README:

> As of Sept 29, 2023, Neon is no longer committing to pg_embedding.
> 
> Support will remain in place for existing users of the extension, but we strongly encourage migrating to pgvector.

Certainly not averse to supporting it if there is demand though.

**Comment by zerolab** [comment]
uff, I missed that note.
Now found the blog post about pgvector implementing the pg_embedding algorithm - https://neon.tech/blog/pgvector-meets-hnsw-index

Given that the next blog post about vector indexing is about pgvector, and the note above - https://neon.tech/blog/understanding-vector-search-and-hnsw-index-with-pgvector - it is safe to not pursue this any further
